# Generated by Django 3.2.13 on 2022-11-19 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='movie',
            field=models.CharField(max_length=30),
        ),
    ]
