# Generated by Django 3.2.13 on 2022-11-19 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_rename_author_review_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewcomment',
            old_name='author',
            new_name='user',
        ),
    ]
