# Generated by Django 3.2.13 on 2022-11-21 00:48

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_img',
            field=models.ImageField(blank=True, upload_to=accounts.models.user_img_path),
        ),
    ]
