# Generated by Django 3.2.13 on 2022-11-21 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='genre_id',
            field=models.IntegerField(default=-1),
        ),
    ]
