# Generated by Django 3.2.13 on 2022-11-21 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_genre_genre_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='genre_id',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='movie_id',
        ),
    ]
